### ISSUE TITLE
Storyboard

### ISSUE THREAD

**Issue by vivianbuan** [vivianbuan/Search-Engine-for-Software#10]
![2161509576535_ pic](https://user-images.githubusercontent.com/8569948/32301687-3695651e-bf1c-11e7-903a-00d264b1cc90.jpg)

**Comment by MSFeng** [comment]
Try different packages from different scenarios. Note for failure cases as well.

**Comment by danisbet** [comment]
![capstone user flowchart](https://user-images.githubusercontent.com/13786298/32597817-a7eb3d8a-c4ec-11e7-9f64-d247e8924613.jpg)

Here's a flowchart of the user experience. Text floating around is a question asked to the user during the process. Text in a box is the user's response. Anything in a diamond is a user's action. I'm using this flowchart to come up with storyboarding ideas and draw them out.

This also surfaced a couple of interesting ideas:
1.  Users may want to quickly replace an item that they're comparing - we probably want the carousel to still be on the page during the comparison so they can drag a new item in.
2.  The user might not be looking for packages whatsoever when we show the carousel. Maybe we should filter any package related results out of the regular results that appear below the carousel.
3.   What do we do when our comparison tool isn't enough for a user to decide on a package? Do we show results that only have to do with the compared packages?

**Comment by danisbet** [comment]
Other storyboards:
Situation 1: Absolutely not looking for a package - ignores carousel
![storyboard regular search results under carousel](https://user-images.githubusercontent.com/13786298/32598122-b42cea16-c4ed-11e7-9220-a3c464d654e0.jpg)

Situation 2: The guy just wants to remind himself of the package name he was told to use. In the end, he just wants to evaluate packages the old fashioned way.
![storyboard show regular search results](https://user-images.githubusercontent.com/13786298/32598166-d80c3306-c4ed-11e7-834c-29446728092d.jpg)

Situation 3: There are way too many potential packages. The guy just wants to compare each one quickly.
![storyboard - quickly add new item to compare](https://user-images.githubusercontent.com/13786298/32598191-e9768696-c4ed-11e7-8353-d01c6f9fa905.jpg)
