### ISSUE TITLE
More on story board

### ISSUE THREAD

**Issue by vivianbuan** [vivianbuan/Search-Engine-for-Software#15]
Add more use cases and consider some corner(failing) cases on top of the original use case.

**Comment by choo8** [comment]
## Feedback from Andrew & Marti:
### Andrew:
* Showing features is important
* Run through a couple more use cases to see if we have features missing for other usage scenarios. Can show how our app would work differently with different use cases.
### Marti:
* Think about failure cases and how our app would handle them. 
* Branch out a bunch of scenarios, possibly different roles like manager, developer etc.
* Potentially can lay out a flow chart to see how our app would work for many cases expected and unexpected?
